# Generated by Django 3.2.8 on 2021-12-02 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import foods.models
import foods.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to=foods.utils.random_filename)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to=foods.utils.random_filename)),
            ],
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate', enumchoicefield.fields.EnumChoiceField(enum_class=foods.models.RateTypes, max_length=2)),
                ('contents', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_reviews', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='foods.food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='foods.foodcategory'),
        ),
    ]
