# Generated by Django 3.2.8 on 2021-12-06 10:10

import deufood.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to=deufood.utils.random_filename),
        ),
    ]
